on:
 schedule:
   - cron: "0 */24 * * *"
 workflow_dispatch:

jobs:
  health-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check health of Render deployed web app
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://fullstackopen-phonebook-cicd-pipeline.onrender.com/